const API_URL =
    location.hostname == "127.0.0.1" || location.hostname == "localhost"
        ? "http://localhost:3000"
        : "https://stocks-backend-production.up.railway.app";

export async function getCryptoCoins() {
    const response = await fetch(`${API_URL}/api/crypto`, {
        method: "GET",
    });

    if (!response.ok) {
        throw new Error("Something went wrong.");
    }

    return await response.json();
}

export function getCryptoMetadata(ids) {
    return {
        1: {
            id: 1,
            name: "Bitcoin",
            symbol: "BTC",
            category: "coin",
            description:
                "Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,498,706. The last known price of Bitcoin is 27,026.07770686 USD and is up 2.17 over the last 24 hours. It is currently trading on 10483 active market(s) with $13,842,361,865.98 traded over the last 24 hours. More information can be found at https://bitcoin.org/.",
            slug: "bitcoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
            subreddit: "bitcoin",
            notice: "",
            tags: [
                "mineable",
                "pow",
                "sha-256",
                "store-of-value",
                "state-channel",
                "coinbase-ventures-portfolio",
                "three-arrows-capital-portfolio",
                "polychain-capital-portfolio",
                "binance-labs-portfolio",
                "blockchain-capital-portfolio",
                "boostvc-portfolio",
                "cms-holdings-portfolio",
                "dcg-portfolio",
                "dragonfly-capital-portfolio",
                "electric-capital-portfolio",
                "fabric-ventures-portfolio",
                "framework-ventures-portfolio",
                "galaxy-digital-portfolio",
                "huobi-capital-portfolio",
                "alameda-research-portfolio",
                "a16z-portfolio",
                "1confirmation-portfolio",
                "winklevoss-capital-portfolio",
                "usv-portfolio",
                "placeholder-ventures-portfolio",
                "pantera-capital-portfolio",
                "multicoin-capital-portfolio",
                "paradigm-portfolio",
                "bitcoin-ecosystem",
                "ftx-bankruptcy-estate",
            ],
            "tag-names": [
                "Mineable",
                "PoW",
                "SHA-256",
                "Store Of Value",
                "State Channel",
                "Coinbase Ventures Portfolio",
                "Three Arrows Capital Portfolio",
                "Polychain Capital Portfolio",
                "Binance Labs Portfolio",
                "Blockchain Capital Portfolio",
                "BoostVC Portfolio",
                "CMS Holdings Portfolio",
                "DCG Portfolio",
                "DragonFly Capital Portfolio",
                "Electric Capital Portfolio",
                "Fabric Ventures Portfolio",
                "Framework Ventures Portfolio",
                "Galaxy Digital Portfolio",
                "Huobi Capital Portfolio",
                "Alameda Research Portfolio",
                "a16z Portfolio",
                "1Confirmation Portfolio",
                "Winklevoss Capital Portfolio",
                "USV Portfolio",
                "Placeholder Ventures Portfolio",
                "Pantera Capital Portfolio",
                "Multicoin Capital Portfolio",
                "Paradigm Portfolio",
                "Bitcoin Ecosystem",
                "FTX Bankruptcy Estate ",
            ],
            "tag-groups": [
                "OTHERS",
                "ALGORITHM",
                "ALGORITHM",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "CATEGORY",
                "PLATFORM",
                "CATEGORY",
            ],
            urls: {
                website: ["https://bitcoin.org/"],
                twitter: [],
                message_board: ["https://bitcointalk.org"],
                chat: [],
                facebook: [],
                explorer: [
                    "https://blockchain.info/",
                    "https://live.blockcypher.com/btc/",
                    "https://blockchair.com/bitcoin",
                    "https://explorer.viabtc.com/btc",
                    "https://www.oklink.com/btc",
                ],
                reddit: ["https://reddit.com/r/bitcoin"],
                technical_doc: ["https://bitcoin.org/bitcoin.pdf"],
                source_code: ["https://github.com/bitcoin/bitcoin"],
                announcement: [],
            },
            platform: null,
            date_added: "2010-07-13T00:00:00.000Z",
            twitter_username: "",
            is_hidden: 0,
            date_launched: "2010-07-13T00:00:00.000Z",
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        2: {
            id: 2,
            name: "Litecoin",
            symbol: "LTC",
            category: "coin",
            description:
                "Litecoin (LTC) is a cryptocurrency . Users are able to generate LTC through the process of mining. Litecoin has a current supply of 84,000,000 with 73,704,776.72743528 in circulation. The last known price of Litecoin is 65.29449516 USD and is up 2.43 over the last 24 hours. It is currently trading on 1005 active market(s) with $232,843,374.28 traded over the last 24 hours. More information can be found at https://litecoin.org/.",
            slug: "litecoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
            subreddit: "litecoin",
            notice: "",
            tags: ["mineable", "pow", "scrypt", "medium-of-exchange"],
            "tag-names": ["Mineable", "PoW", "Scrypt", "Medium of Exchange"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "INDUSTRY"],
            urls: {
                website: ["https://litecoin.org/"],
                twitter: ["https://twitter.com/litecoin"],
                message_board: [
                    "https://litecointalk.io/",
                    "https://litecoin-foundation.org/",
                ],
                chat: ["https://telegram.me/litecoin"],
                facebook: [],
                explorer: [
                    "https://blockchair.com/litecoin",
                    "https://chainz.cryptoid.info/ltc/",
                    "http://explorer.litecoin.net/chain/Litecoin",
                    "https://bscscan.com/token/0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
                ],
                reddit: ["https://reddit.com/r/litecoin"],
                technical_doc: [],
                source_code: ["https://github.com/litecoin-project/litecoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=47417.0",
                ],
            },
            platform: {
                id: "2502",
                name: "Huobi Token",
                slug: "htx-token",
                symbol: "HT",
                token_address: "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
            },
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "litecoin",
            is_hidden: 0,
            date_launched: null,
            contract_address: [
                {
                    contract_address:
                        "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
                    platform: {
                        name: "HECO",
                        coin: {
                            id: "2502",
                            name: "Huobi Token",
                            symbol: "HT",
                            slug: "htx-token",
                        },
                    },
                },
                {
                    contract_address:
                        "0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
                    platform: {
                        name: "BNB Smart Chain (BEP20)",
                        coin: {
                            id: "1839",
                            name: "BNB",
                            symbol: "BNB",
                            slug: "bnb",
                        },
                    },
                },
                {
                    contract_address:
                        "0x13e93721dc992b3e14333dbdb48c0e7ec55431c3",
                    platform: {
                        name: "Hoo Smart Chain",
                        coin: {
                            id: "15165",
                            name: "Hoo Smart Chain",
                            symbol: "HSC",
                            slug: "hoo-smart-chain",
                        },
                    },
                },
            ],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        3: {
            id: 3,
            name: "Namecoin",
            symbol: "NMC",
            category: "coin",
            description:
                "Namecoin (NMC) is a cryptocurrency . Users are able to generate NMC through the process of mining. Namecoin has a current supply of 14,736,400. The last known price of Namecoin is 1.22934034 USD and is down -13.12 over the last 24 hours. It is currently trading on 7 active market(s) with $12,655.64 traded over the last 24 hours. More information can be found at https://www.namecoin.org/.",
            slug: "namecoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3.png",
            subreddit: "namecoin",
            notice: "",
            tags: ["mineable", "pow", "sha-256", "platform"],
            "tag-names": ["Mineable", "PoW", "SHA-256", "Platform"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"],
            urls: {
                website: ["https://www.namecoin.org/"],
                twitter: ["https://twitter.com/Namecoin"],
                message_board: [],
                chat: ["https://www.namecoin.org/resources/chat/"],
                facebook: [],
                explorer: [
                    "https://nmc.tokenview.com/",
                    "https://www.namebrow.se/",
                    "https://namecha.in/",
                    "https://chainz.cryptoid.info/nmc/",
                ],
                reddit: ["https://reddit.com/r/namecoin"],
                technical_doc: [
                    "https://www.namecoin.org/resources/whitepaper/",
                ],
                source_code: ["https://github.com/namecoin"],
                announcement: ["https://bitcointalk.org/?topic=6017.0"],
            },
            platform: null,
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "Namecoin",
            is_hidden: 0,
            date_launched: null,
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        4: {
            id: 4,
            name: "Terracoin",
            symbol: "TRC",
            category: "coin",
            description:
                "Terracoin (TRC) is a cryptocurrency launched in 2012. Users are able to generate TRC through the process of mining. Terracoin has a current supply of 22,935,396.430361 with 0 in circulation. The last known price of Terracoin is 0.01082671 USD and is up 2.05 over the last 24 hours. It is currently trading on 2 active market(s) with $114.69 traded over the last 24 hours. More information can be found at http://www.terracoin.io/.",
            slug: "terracoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/4.png",
            subreddit: "terracoin",
            notice: "",
            tags: ["mineable", "pow", "sha-256", "masternodes"],
            "tag-names": ["Mineable", "PoW", "SHA-256", "Masternodes"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"],
            urls: {
                website: ["http://www.terracoin.io/"],
                twitter: ["https://twitter.com/Terracoin_TRC"],
                message_board: ["https://medium.com/@clockuniverse"],
                chat: [
                    "https://mattermost.terracoin.io/",
                    "https://t.me/terracoin",
                ],
                facebook: [],
                explorer: [
                    "https://insight.terracoin.io/",
                    "https://explorer.terracoin.io/chain/Terracoin",
                ],
                reddit: ["https://reddit.com/r/terracoin"],
                technical_doc: ["https://wiki.terracoin.io/view/Whitepaper"],
                source_code: ["https://github.com/terracoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=1364146.0",
                ],
            },
            platform: null,
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "Terracoin_TRC",
            is_hidden: 0,
            date_launched: "2012-10-26T00:00:00.000Z",
            contract_address: [],
            self_reported_circulating_supply: 22935396.430361,
            self_reported_tags: null,
            self_reported_market_cap: 248165.2892631097,
            infinite_supply: false,
        },
        5: {
            id: 5,
            name: "Peercoin",
            symbol: "PPC",
            category: "coin",
            description:
                "Peercoin (PPC) is a cryptocurrency . Users are able to generate PPC through the process of mining. Peercoin has a current supply of 28,389,194.14025835. The last known price of Peercoin is 0.2946356 USD and is up 0.21 over the last 24 hours. It is currently trading on 29 active market(s) with $1,026.47 traded over the last 24 hours. More information can be found at http://www.peercoin.net.",
            slug: "peercoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/5.png",
            subreddit: "peercoin",
            notice: "",
            tags: [
                "mineable",
                "hybrid-pow-pos",
                "sha-256",
                "medium-of-exchange",
                "store-of-value",
                "payments",
                "staking",
            ],
            "tag-names": [
                "Mineable",
                "Hybrid - PoW & PoS",
                "SHA-256",
                "Medium of Exchange",
                "Store Of Value",
                "Payments",
                "Staking",
            ],
            "tag-groups": [
                "OTHERS",
                "ALGORITHM",
                "ALGORITHM",
                "INDUSTRY",
                "CATEGORY",
                "INDUSTRY",
                "CATEGORY",
            ],
            urls: {
                website: ["http://www.peercoin.net"],
                twitter: ["https://twitter.com/PeercoinPPC"],
                message_board: ["https://talk.peercoin.net"],
                chat: ["https://t.me/peercoin", "https://discord.gg/m294ReV"],
                facebook: [],
                explorer: [
                    "https://chainz.cryptoid.info/ppc/",
                    "https://explorer.peercoin.net/",
                    "https://etherscan.io/token/0x044d078F1c86508e13328842Cc75AC021B272958",
                    "https://polygonscan.com/token/0x91E7E32C710661C44ae44D10Aa86135d91C3Ed65",
                ],
                reddit: ["https://reddit.com/r/peercoin"],
                technical_doc: ["https://docs.peercoin.net/"],
                source_code: ["https://github.com/peercoin/peercoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=101820.0",
                ],
            },
            platform: {
                id: "1027",
                name: "Ethereum",
                slug: "ethereum",
                symbol: "ETH",
                token_address: "0x044d078F1c86508e13328842Cc75AC021B272958",
            },
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "PeercoinPPC",
            is_hidden: 0,
            date_launched: null,
            contract_address: [
                {
                    contract_address:
                        "0x044d078F1c86508e13328842Cc75AC021B272958",
                    platform: {
                        name: "Ethereum",
                        coin: {
                            id: "1027",
                            name: "Ethereum",
                            symbol: "ETH",
                            slug: "ethereum",
                        },
                    },
                },
                {
                    contract_address:
                        "0x91E7E32C710661C44ae44D10Aa86135d91C3Ed65",
                    platform: {
                        name: "Polygon",
                        coin: {
                            id: "3890",
                            name: "Polygon",
                            symbol: "MATIC",
                            slug: "polygon",
                        },
                    },
                },
            ],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        6: {
            id: 6,
            name: "Novacoin",
            symbol: "NVC",
            category: "coin",
            description:
                "Novacoin (NVC) is a cryptocurrency launched in 2013. Users are able to generate NVC through the process of mining. Novacoin has a current supply of 2,335,756.713897 with 0 in circulation. The last known price of Novacoin is 0.02489509 USD and is up 2.18 over the last 24 hours. It is currently trading on 2 active market(s) with $0.00 traded over the last 24 hours. More information can be found at https://nova-coin.org.",
            slug: "novacoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/6.png",
            subreddit: "NovacoinCommunity/",
            notice: "",
            tags: ["mineable", "hybrid-pow-pos", "scrypt"],
            "tag-names": ["Mineable", "Hybrid - PoW & PoS", "Scrypt"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM"],
            urls: {
                website: ["https://nova-coin.org", "https://novacoin.one"],
                twitter: ["https://twitter.com/Novacoin_NVC"],
                message_board: [],
                chat: [
                    "https://discord.gg/6juXnsSkGa",
                    "https://t.me/NovaCoin_EN",
                ],
                facebook: [],
                explorer: [
                    "https://chainz.cryptoid.info/nvc/",
                    "https://explorer.novaco.in/",
                    "http://nvc-explorer.ewmcx.info/",
                ],
                reddit: ["https://reddit.com/r/NovacoinCommunity/"],
                technical_doc: [
                    "https://github.com/novacoin-project/novacoin/wiki",
                ],
                source_code: ["https://github.com/novacoin-project/novacoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=5189560.0",
                ],
            },
            platform: {
                id: "1839",
                name: "BNB",
                slug: "bnb",
                symbol: "BNB",
                token_address: "0xbf84720097de111a80f46f9d077643967042841a",
            },
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "Novacoin_NVC",
            is_hidden: 0,
            date_launched: "2013-02-05T00:00:00.000Z",
            contract_address: [
                {
                    contract_address:
                        "0xbf84720097de111a80f46f9d077643967042841a",
                    platform: {
                        name: "BNB Smart Chain (BEP20)",
                        coin: {
                            id: "1839",
                            name: "BNB",
                            symbol: "BNB",
                            slug: "bnb",
                        },
                    },
                },
            ],
            self_reported_circulating_supply: 4240602.558217,
            self_reported_tags: null,
            self_reported_market_cap: 105543.71031949625,
            infinite_supply: false,
        },
        7: {
            id: 7,
            name: "Devcoin",
            symbol: "DVC",
            category: "coin",
            description:
                "Devcoin (DVC) is a cryptocurrency launched in 2011. Users are able to generate DVC through the process of mining. Devcoin has a current supply of 15,167,257,500. The last known price of Devcoin is 0.00002298 USD and is up 0.00 over the last 24 hours. More information can be found at https://www.devcoin.org/.",
            slug: "devcoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/7.png",
            subreddit: "devcoin",
            notice: "",
            tags: ["mineable"],
            "tag-names": ["Mineable"],
            "tag-groups": ["OTHERS"],
            urls: {
                website: ["https://www.devcoin.org/"],
                twitter: ["https://twitter.com/_Devcoin"],
                message_board: [],
                chat: ["https://t.me/Devcoins"],
                facebook: ["https://www.facebook.com/devcoin"],
                explorer: ["https://chainz.cryptoid.info/dvc/"],
                reddit: ["https://reddit.com/r/devcoin"],
                technical_doc: ["https://www.devtome.com/devcoin"],
                source_code: ["https://github.com/devcoin/core"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=233997.0",
                ],
            },
            platform: null,
            date_added: "2013-04-28T00:00:00.000Z",
            twitter_username: "_Devcoin",
            is_hidden: 0,
            date_launched: "2011-07-21T00:00:00.000Z",
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        8: {
            id: 8,
            name: "Feathercoin",
            symbol: "FTC",
            category: "coin",
            description:
                "Feathercoin (FTC) is a cryptocurrency . Users are able to generate FTC through the process of mining. Feathercoin has a current supply of 336,000,000 with 236,600,238 in circulation. The last known price of Feathercoin is 0.00189419 USD and is down -3.35 over the last 24 hours. It is currently trading on 11 active market(s) with $1.90 traded over the last 24 hours. More information can be found at http://feathercoin.com.",
            slug: "feathercoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/8.png",
            subreddit: "FeatherCoin",
            notice: "",
            tags: [
                "mineable",
                "pow",
                "neoscrypt",
                "medium-of-exchange",
                "collectibles-nfts",
                "payments",
            ],
            "tag-names": [
                "Mineable",
                "PoW",
                "NeoScrypt",
                "Medium of Exchange",
                "Collectibles & NFTs",
                "Payments",
            ],
            "tag-groups": [
                "OTHERS",
                "ALGORITHM",
                "ALGORITHM",
                "INDUSTRY",
                "CATEGORY",
                "INDUSTRY",
            ],
            urls: {
                website: ["http://feathercoin.com"],
                twitter: ["https://twitter.com/Feathercoin"],
                message_board: ["https://forum.feathercoin.com"],
                chat: ["https://telegram.me/feathercoinofficial"],
                facebook: [],
                explorer: [
                    "http://explorer.feathercoin.com/",
                    "https://chainz.cryptoid.info/ftc/",
                    "https://fsight.chain.tips/",
                ],
                reddit: ["https://reddit.com/r/FeatherCoin"],
                technical_doc: ["https://feathercoin.com/about/"],
                source_code: ["https://github.com/FeatherCoin/Feathercoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=178286.0",
                ],
            },
            platform: null,
            date_added: "2013-05-03T00:00:00.000Z",
            twitter_username: "Feathercoin",
            is_hidden: 0,
            date_launched: null,
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        9: {
            id: 9,
            name: "Mincoin",
            symbol: "MNC",
            category: "coin",
            description:
                "Mincoin (MNC) is a cryptocurrency . Users are able to generate MNC through the process of mining. Mincoin has a current supply of 6,228,916.8879491. The last known price of Mincoin is 0.07458228 USD and is up 0.00 over the last 24 hours. More information can be found at https://www.mincoin.us/.",
            slug: "mincoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/9.png",
            subreddit: "MinCoin",
            notice: "",
            tags: ["mineable", "pow", "scrypt"],
            "tag-names": ["Mineable", "PoW", "Scrypt"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM"],
            urls: {
                website: ["https://www.mincoin.us/"],
                twitter: ["https://twitter.com/mincoinus"],
                message_board: ["https://www.mincoinforum.com"],
                chat: [],
                facebook: [],
                explorer: [
                    "http://cryptoexplore.com",
                    "https://www.mincoinexplorer.com/",
                ],
                reddit: ["https://reddit.com/r/MinCoin"],
                technical_doc: [
                    "https://github.com/mincoin/mincoin-whitepaper/blob/master/docs/mincoin-whitepaper.pdf",
                ],
                source_code: ["https://github.com/mincoin"],
                announcement: [
                    "https://bitcointalk.org/index.php?topic=165397.0",
                ],
            },
            platform: null,
            date_added: "2013-05-03T00:00:00.000Z",
            twitter_username: "mincoinus",
            is_hidden: 0,
            date_launched: null,
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
        10: {
            id: 10,
            name: "Freicoin",
            symbol: "FRC",
            category: "coin",
            description:
                "Freicoin (FRC) is a cryptocurrency . Users are able to generate FRC through the process of mining. Freicoin has a current supply of 100,000,000 with 0 in circulation. The last known price of Freicoin is 0.0008118 USD and is up 2.18 over the last 24 hours. It is currently trading on 1 active market(s) with $0.00 traded over the last 24 hours. More information can be found at http://freico.in.",
            slug: "freicoin",
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/10.png",
            subreddit: "",
            notice: "",
            tags: ["mineable", "pow", "sha-256"],
            "tag-names": ["Mineable", "PoW", "SHA-256"],
            "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM"],
            urls: {
                website: ["http://freico.in"],
                twitter: ["https://twitter.com/Freicoin"],
                message_board: ["https://freicoinalliance.com/"],
                chat: [],
                facebook: [],
                explorer: ["http://freicoin.info/chain/Freicoin"],
                reddit: [],
                technical_doc: ["http://freico.in/docs/freimarkets.pdf"],
                source_code: ["https://github.com/freicoin/freicoin"],
                announcement: [],
            },
            platform: null,
            date_added: "2013-05-03T00:00:00.000Z",
            twitter_username: "Freicoin",
            is_hidden: 0,
            date_launched: null,
            contract_address: [],
            self_reported_circulating_supply: null,
            self_reported_tags: null,
            self_reported_market_cap: null,
            infinite_supply: false,
        },
    };
}
